### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by gerchicov-bp** [Visput/BiometricAuthenticationFacade#2]
Импорт библиотек через `@` не работает, если в проект подключены модули. Поправьте пожалуйста

**Comment by Visput** [comment]
Можете расписать подробней, что не работает?

Я создал новый проект, добавил pod: 

```
use_frameworks!

target 'VPBiometricsTest' do
    pod "BiometricAuthenticationFacade"
end
```

В классе, в котором хочу использовать библиотеку, импортировал модуль:

```
@import BiometricAuthenticationFacade;
```

Создал instance:

```
VPBiometricAuthenticationFacade *facade = [VPBiometricAuthenticationFacade new];
```

Проект комплируется.

**Comment by gerchicov-bp** [comment]
я импортировал через "drag-n-drop".
Смотрите:
http://stackoverflow.com/questions/32044830/error-while-registering-with-gcm-for-ios-app
Если коротко, то не понятно, зачем они вообще вводили этот синтаксис, если он в половине проектов не будет работать, но если заменить все `@import` на соответствующие `#import`, то будет работать всегда.

**Comment by Visput** [comment]
Попробовал создать новый проект и использовать drag-n-drop.
В результате это не работает:
`#import <BiometricAuthenticationFacade/VPBiometricAuthenticationFacade.h>`

Корректно работает это:
`@import VPBiometricAuthenticationFacade;`

В этом заключается Ваша проблема?

**Comment by gerchicov-bp** [comment]
сори, нет, я перетащил 2 файла исходников в свой проект (собственно а смысл импортировать проект, в котором всего 2 файла, один из которых все равно будет "public" - независимо от того, каким способом он будет импортирован)

И правильно - вашим способом исходники остаются в своем проекте без модулей и не будут ругаться на `@`. Чтобы заработало с `#` нужно то ли тип библиотеки менять в настройках, то ли указать в настройках, где лежит этот h файл

**Comment by Visput** [comment]
Тогда не понятно, чем я могу помочь и что мне нужно исправить.
В Read.me указано два способа установки библиотеки, способ, которым Вы пользуетесь, там не указан.
