### ISSUE TITLE
Лишний код?

### ISSUE THREAD

**Issue by gerchicov-bp** [Visput/BiometricAuthenticationFacade#3]
Методы ]enableAuthenticationForFeature...`и`disableAuthenticationForFeature...` вызываются через dispatch_async? Зачем? Притом, что даже в статье на хабре этого нет и из-за этого придется работать с простыми операциями как с асинхронными.
Зато в эти методы нельзя передавать nil вместо пустых блоков, потому что проверки на него нет

**Comment by Visput** [comment]
Внутренняя реализация `disableAuthenticationForFeature` использует асинхронный вызов:
`[self.authenticationContext evaluatePolicy:LAPolicyDeviceOwnerAuthenticationWithBiometrics localizedReason:reason reply:^(BOOL success, NSError *error) {`

Поэтому этот метод реализован асинхронно.

`enableAuthenticationForFeature` сделан ассинхронным для симметрии с `disableAuthenticationForFeature`.
